config/routes.rb
JobBoard::Application.routes.draw do
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  root      "job_postings#index"
  resources :companies
  resources :job_postings
  resources :job_experiences
  resources :job_types
  resources :job_skills
end

app/models/company.rb
class Company < ActiveRecord::Base
  validates :name, :address, :url, presence: true
  validates :show_address, inclusion: {in: [true, false], message: 'requires a true or false value'}
  validates :show_as_customer,  inclusion: {in: [true, false], message: 'requires a true or false value'}
  validates :url, uri: { format: /(^$)|(^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?$)/ix }
end

app/models/job_experience.rb
class JobExperience < ActiveRecord::Base
  validates :name, presence: true
  has_many :job_postings
end

app/models/job_posting.rb
class JobPosting < ActiveRecord::Base
  validates :job_experience_id, :job_type_id, :title, :would_have_done, :compensation, :nice_to_have , presence: true
  validates :relocation, inclusion: {in: [true, false], message: 'requires a true or false value'}
  validates :remote, inclusion: {in: [true, false], message: 'requires a true or false value'}
  validates :freelance, inclusion: {in: [true, false], message: 'requires a true or false value'}

  belongs_to :job_experience
  belongs_to :job_type

  delegate :name, to: :job_experience, prefix: true
  delegate :name, to: :job_type, prefix: true
end

app/models/job_skill.rb
class JobSkill < ActiveRecord::Base
  validates :name, :version, presence: true
end

app/models/job_type.rb
class JobType < ActiveRecord::Base
  validates :name, :skills, presence: true
  has_many :job_postings
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  def index
    @companies = Company.all
  end

  def show
  end

  def new
    @company = Company.new
  end

  def edit
  end

  def create
    @company = Company.new(company_params)
    if @company.save
      redirect_to @company, notice: 'Company was successfully created.'
    else
      render 'new'
    end
  end

  def update
    # Slightly different because of the boolen values and validation. Other wise .find(company_params)
    # would work.

    @company = Company.find(params[:id])

    if @company.update(company_params)
      redirect_to @company, notice: 'The Company was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @company.destroy
    redirect_to companies_url
  end

  private
  def set_company
    @company = Company.find(params[:id])
  end

  def company_params
      params.require(:company).permit(:name, :url, :address, :show_address, :show_as_customer)
  end

end

app/controllers/job_experiences_controller.rb
class JobExperiencesController < ApplicationController
  before_action :set_job_experience, only: [:show, :edit, :update, :destroy]

  def index
   @job_experiences = JobExperience.all
  end

  def show
  end

  def new
    @job_experience = JobExperience.new
  end

  def edit
  end

  def create
    @job_experience = JobExperience.new(job_experience_params)
    if @job_experience.save
      redirect_to @job_experience, notice: 'Job Experience was sucessfully created'
    else
      render 'new'
    end
  end

  def update
    @job_experience = JobExperience.find(params[:id])

    if @job_experience.update(job_experience_params)
      redirect_to @job_experience, notice: 'The Job Experience was sucessfully updated'
    else
      render 'edit'
    end
  end

  def destroy
    @job_experience.destroy
    redirect_to job_experiences_url
  end

  private
  def set_job_experience
    @job_experience = JobExperience.find(params[:id])
  end

  def job_experience_params
    params.require(:job_experience).permit(:name)
  end

end

app/controllers/job_postings_controller.rb
class JobPostingsController < ApplicationController
  before_action :set_job_posting, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index, :show]

  def index
    @job_postings = JobPosting.includes(:job_experience, :job_type)
  end

  def show
  end

  def new
    @job_posting = JobPosting.new
  end

  def edit
  end

  def create
    @job_posting = JobPosting.new(job_posting_params)
    if @job_posting.save
      redirect_to @job_posting, notice: 'Job posting was successfully created.'
    else
      render 'new'
    end
  end

  def update
    @job_posting = JobPosting.find(params[:id])

    if @job_posting.update(job_posting_params)
      redirect_to @job_posting, notice: 'The Job posting was sucessfully updated'
    else
      render  'edit'
    end
  end

  def destroy
    @job_posting.destroy
    redirect_to job_postings_url
  end

  private
  def set_job_posting
    @job_posting = JobPosting.find(params[:id])
  end

  def job_posting_params
    params.require(:job_posting).permit(:job_experience_id, :job_type_id, :title, :relocation, :remote, :freelance, :would_have_done, :compensation, :nice_to_have)
  end

end

app/controllers/job_skills_controller.rb
class JobSkillsController < ApplicationController
  before_action :set_job_skill, only: [:show, :edit, :update, :destroy]

  def index
    @job_skills = JobSkill.all
    @sorted_skills = @job_skills.order("name, version")
  end

  def show
  end

  def new
    @job_skill = JobSkill.new
  end

  def edit
  end

  def create
    @job_skill = JobSkill.new(job_skill_params)
    if @job_skill.save
      redirect_to @job_skill, notice: 'Job skill was sucessfully saved'
    else
      render 'new'
    end
  end

  def update
    @job_skill = JobSkill.find(params[:id])

    if @job_skill.update(job_skill_params)
      redirect_to @job_skill, notice: 'The Job skill was successfully updated'
    else
      render 'edit'
    end
  end

  def destroy
    @job_skill.destroy
    redirect_to job_skills_url
  end

  private

    def set_job_skill
      @job_skill = JobSkill.find(params[:id])
    end

    def job_skill_params
      params.require(:job_skill).permit(:name, :version)
    end

end

app/controllers/job_types_controller.rb
class JobTypesController < ApplicationController
  before_action :set_job_posting, only: [:show, :edit, :update, :destroy]

  def index
    @job_types = JobType.all
  end

  def show
  end

  def new
    @job_type = JobType.new
  end

  def edit
  end

  def create
    @job_type = JobType.new(job_type_params)
    if @job_type.save
      redirect_to @job_type, notice: 'Job type was sucessfully saved'
    else
      render 'new'
    end
  end

  def update
    @job_type = JobType.find(params[:id])

    if @job_type.update(job_type_params)
      redirect_to @job_type, notice: 'The Job type was sucessfully updated'
    else
      render 'edit'
    end
  end

  def destroy
    @job_type.destroy
    redirect_to job_types_url
  end

  private

    def set_job_posting
      @job_type = JobType.find(params[:id])
    end

    def job_type_params
      params.require(:job_type).permit(:name, :skills)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/companies/_form.html.haml
= form_for company do |f|
  - if company.errors.any?
    #errorExplanation
      %h2
        = pluralize(company.errors.count, "error")
        prohibited this company from being saved:
      %ul
        - company.errors.full_messages.each do |msg|
          %li= msg
  %div
    = f.label :name
    = f.text_field :name
  %div
    = f.label :address
    = f.text_field :address

  %div
    = f.label :url
    = f.text_area :url
  %div
    = f.label :show_address
    = f.check_box :show_address
  %div
    = f.label :show_as_customer
    = f.check_box :show_as_customer
  %div
    = f.submit

app/views/companies/edit.html.haml
%h1 Editing company
= render 'form', company: @company
= link_to 'Show', @company
|
\#{link_to 'Back', companies_path}

app/views/companies/index.html.haml
%h1 Listing Companies
%table
  %tr
    %th Name
    %th Address
    %th URL
    %th Show Address
    %th Show as Customer
    %th{colspan: "3"} Actions
  - @companies.each do |company|
    %tr
      %td= company.name
      %td= company.address
      %td= company.url
      %td= company.show_address
      %td= company.show_as_customer
      %td= link_to 'Show', company
      %td= link_to 'Edit', edit_company_path(company)
      %td= link_to 'Destroy', company, method: :delete, |
          data: { confirm: 'Are you sure?' }        |
%br/
= link_to 'New Company', new_company_path

app/views/companies/new.html.haml
%h1 New company
= render 'form', company: @company
= link_to 'Back', companies_path

app/views/companies/show.html.haml
%p#notice= notice
%div
  %h2 Name:
  = @company.name
%div
  %h2 Url:
  = link_to @company.name, @company.url
%div
  %h2 Address:
  = @company.address
%div
  %h2 Show address:
  = @company.show_address
%div
  %h2 Show as customer:
  = @company.show_as_customer
= link_to 'Edit', edit_company_path(@company)
|
\#{link_to 'Back', companies_path}

app/views/job_experiences/_form.html.haml
= form_for job_experience do |f|
  - if job_experience.errors.any?
    #errorExplanation
      %h2
        = pluralize(job_experience.errors.count, "error")
        prohibited this experience from being saved:

      %ul
      - job_experience.errors.full_messages.each do |msg|
        %li= msg

  %div
    = f.label :name
    = f.text_field :name

  %div
    = f.submit

app/views/job_experiences/edit.html.haml
%h1 Editing Job Experience
= render 'form', job_experience: @job_experience
= link_to 'Show', @job_experience
|
\#{link_to 'Back', job_experiences_path}

app/views/job_experiences/index.html.haml
%h1 Job Experience
%table
  %tr
    %th Experience
    %th{colspan: "3"} Actions
  - @job_experiences.each do |experience|
    %tr
      %td= experience.name
      %td= link_to 'Show', experience
      %td= link_to 'Edit', edit_job_experience_path(experience)
      %td= link_to 'Destroy', experience, method: :delete, |
           data: {confirm: 'Are you sure?' }       |

%br/
= link_to "New Job Experience", new_job_experience_path

app/views/job_experiences/new.html.haml
%h1 New Job Experience
= render 'form', job_experience: @job_experience
= link_to 'Back', job_experiences_path

app/views/job_experiences/show.html.haml
%p#notice= notice
%div
  %h2 Name:
  = @job_experience.name

= link_to 'Edit', edit_job_experience_path(@job_experience)
|
\#{link_to 'Back', job_experiences_path}

app/views/job_postings/_form.html.haml
= form_for job_posting do |f|
  - if job_posting.errors.any?
    #errorExplanation
      %h2
        = pluralize(job_posting.errors.count, "error")
        prohibited this company from being saved:
      %ul
      - job_posting.errors.full_messages.each do |msg|
        %li= msg

  %div
    = f.label :job_experience_id
    = f.collection_select(:job_experience_id, JobExperience.all, :id, :name)
  %div
    = f.label :job_type_id
    = f.collection_select(:job_type_id, JobType.all, :id, :name)
  %div
    = f.label :title
    = f.text_field :title
  %div
    = f.label :relocation
    = f.check_box :relocation
  %div
    = f.label :remote
    = f.check_box :remote
  %div
    = f.label :freelance
    = f.check_box :freelance
  %div
    = f.label :would_have_done
    = f.text_field :would_have_done
  %div
    = f.label :compensation
    = f.text_field :compensation
  %div
    = f.label :nice_to_have
    = f.text_field :nice_to_have
  %div
    = f.submit

app/views/job_postings/edit.html.haml
%h1 Editing Job Posting
= render 'form', job_posting: @job_posting
= link_to 'Show', @job_posting
|
\#{link_to 'Back', job_postings_path}

app/views/job_postings/index.html.haml
%h1 Job Postings
%table
  %tr
    %th Experience
    %th Category
    %th Title
    %th Relocation
    %th Remote
    %th Freelance
    %th Would have done
    %th Nice to have
    %th Compensation
    -if current_user
      %th{colspan: "3"} Actions
  - @job_postings.each do |posting|
    %tr
      %td= posting.job_experience.name
      %td= posting.job_type.name
      %td= posting.title
      %td= posting.relocation
      %td= posting.remote
      %td= posting.freelance
      %td= posting.would_have_done
      %td= posting.nice_to_have
      %td= posting.compensation
      -if current_user
        %td= link_to 'Show', posting
        %td= link_to 'Edit', edit_job_posting_path(posting)
        %td= link_to 'Destroy', posting, method: :delete, |
            data: { confirm: 'Are you sure?' }        |
-if current_user
  %br/
  = link_to 'New posting', new_job_posting_path

app/views/job_postings/new.html.haml
%h1 New Job Posting
= render 'form', job_posting: @job_posting
= link_to 'Back', job_postings_path

app/views/job_postings/show.html.haml
%p#notice= notice
%div
  %h2 Experience:
  = @job_posting.job_experience_name
%div
  %h2 Category:
  = @job_posting.job_type_name
%div
  %h2 Title:
  = @job_posting.title
%div
  %h2 Relocation:
  = @job_posting.relocation
%div
  %h2 Remote Work
  = @job_posting.remote
%div
  %h2 Freelance
  = @job_posting.freelance
%div
  %h2 Would have done
  = @job_posting.would_have_done
%div
  %h2 Compensation
  = @job_posting.compensation
%div
  %h2 Nice to have
  = @job_posting.nice_to_have

= link_to 'Edit', edit_job_posting_path(@job_posting)
|
\#{link_to 'Back', job_postings_path}

app/views/job_skills/_form.html.haml
= form_for job_skill do |f|
  - if job_skill.errors.any?
    #errorExplanation
      %h2
        = pluralize(job_skill.errors.count, 'error')
        prohibited this skill from being saved
      %ul
      - job_skill.errors.full_messages.each do |meg|
        %li= msg

  %div
    = f.label :name
    = f.text_field :name
  %div
    = f.label :version
    = f.text_field :version
  %div
    = f.submit

app/views/job_skills/edit.html.haml
%h1 Editing Job Skill
= render 'form', job_skill: @job_skill
= link_to 'Show', @job_skill
|
\#{link_to 'Back', job_skills_path}

app/views/job_skills/index.html.haml
%h1 Job Skills
%table
  %tr
    %th Name
    %th Version
    %th{colspan: '3'} Actions
  - @sorted_skills.each do |skill|
    %tr
      %td= skill.name
      %td= skill.version
      %td= link_to 'Show', skill
      %td= link_to 'Edit', edit_job_skill_path(skill)
      %td= link_to 'Destroy', skill, method: :delete, |
        data: {confirm: 'Are you sure?'}      |

%br/
=link_to "New Skill", new_job_skill_path

app/views/job_skills/new.html.haml
%h1 New Skill
= render 'form', job_skill: @job_skill
= link_to 'Back', job_postings_path

app/views/job_skills/show.html.haml
%pnotice= notice
%div
  %h2 Skill:
  = @job_skill.name
%div
  %h2 Version
  = @job_skill.version

= link_to 'Edit', edit_job_skill_path(@job_skill)
|
\#{link_to 'Back', job_skills_path}

app/views/job_types/_form.html.haml
= form_for job_type do |f|
  - if job_type.errors.any?
    #errorExplanation
      %h2
        = pluralize(job_type.errors.count, "error")
        prohibited this experience from being saved:

      %ul
      - job_type.errors.full_messages.each do |msg|
        %li= msg

  %div
    = f.label :name
    = f.text_field :name

  %div
    = f.label :skills
    = f.text_field :skills

  %div
    = f.submit

app/views/job_types/edit.html.haml
%h1 Editing Job Type
= render 'form', job_type: @job_type
= link_to 'Show', @job_type
|
\#{link_to 'Back', job_types_path}

app/views/job_types/index.html.haml
%h1 Job Types
%table
  %tr
    %th Name
    %th Skills
    %th{colspan: '3'} Actions
  - @job_types.each do |type|
    %tr
      %td= type.name
      %td= type.skills
      %td= link_to 'Show', type
      %td= link_to 'Edit', edit_job_type_path(type)
      %td= link_to 'Destroy', type, method: :delete, |
            data: { confirm: 'Are you sure?' }    |

%br/
= link_to 'New Type', new_job_type_path

app/views/job_types/new.html.haml
%h1 New Job Type
= render 'form', job_type: @job_type
= link_to 'Back', job_types_path

app/views/job_types/show.html.haml
%p#notice= notice
%div
  %h2 Name:
  = @job_type.name
%div
  %h2 Skills:
  = @job_type.skills

= link_to 'Edit', edit_job_type_path(@job_type)
|
\#{link_to 'Back', job_types_path}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title JobBoard
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    #container
      #user_nav
        - if user_signed_in?
          Logged in as
          = succeed "." do
            %strong= current_user.email
          = link_to 'Edit profile', edit_user_registration_path
          |
          \#{link_to "Logout", destroy_user_session_path, method: :delete}
        - else
          = link_to "Sign up", new_user_registration_path
          |
          \#{link_to "Login", new_user_session_path}
    - flash.each do |name, msg|
      = content_tag :div, msg, id: "flash_#{name}"
    = yield